services:
  database:
    image: postgres:17
    container_name: secret-notes-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: secretuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: secretnotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: