sonar.projectKey=secret-notes
sonar.projectName=Secret Notes
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.tests=backend/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.github/**,**/Dockerfile,**/*.config.js,**/*.config.ts
sonar.test.inclusions=backend/test/**/*.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info